name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    #DockerHub Container Registry:
    #Username: My DockerHub account username
    #Password: Access token created on https://hub.docker.com/settings/security
    #(Both tokens saved on https://github.com/Alessandro1918/ci/settings/secrets/actions)
    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build image
    #   run: docker build -t alessandro1918/nlw-journey:latest .

    # - name: Push image
    #   run: |
    #     docker push ale1918/nlw-journey:abc1234
    #     docker tag ale1918/nlw-journey:abc1234 ale1918/nlw-journey:latest
    #     docker push ale1918/nlw-journey:latest

    #OBS: Pipping 2 tags like this will ensure that the image tagged as "xyz" will remain in the Registry as a backup, when the "old latest" gets overwriten by the "new latest" on the next commit.

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          alessandro1918/nlw-journey:${{ steps.generate_sha.outputs.sha }}
          alessandro1918/nlw-journey:latest
