name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #Generate tag based on commit

    #Login on the container registry

    #V1 - Build image with "docker build" command (docker build -t image-name:tag .):
    - name: Build image
      run: docker build -t alessandro1918/nlw-journey:latest .
